### ISSUE TITLE
Linea de codigo 92.

### ISSUE THREAD

**Issue by rhoguevara** [julcavasquez/mitrivia_dz#3]
![image](https://user-images.githubusercontent.com/112536136/190838909-678472d5-96d0-4200-90ae-6eb13e8b609c.png)

Por buenas practicas, _if_ **intentos >1:** **==>** deberia estar separado un espacio, ejemplo: _if_ **intentos > 1:**

**Comment by julcavasquez** [comment]
se actualizo código aplicando buenas practicas.
