### ISSUE TITLE
Linea de codigo 130.

### ISSUE THREAD

**Issue by rhoguevara** [julcavasquez/mitrivia_dz#4]
![image](https://user-images.githubusercontent.com/112536136/190838959-62a186d9-606d-4be0-a910-c29b3ab0777c.png)

Para buenas practicas; **while num_estrellas.isnumeric()==False:** ==> deberia estar separado una espacio la igualdad, asi como en la linea de codigo 133. Quedaria asi: **while num_estrellas.isnumeric() == False:**
Para no seguir con ello, en muchas lineas de codigo podrias mejorar el espaciado. Good luck!

**Comment by julcavasquez** [comment]
se actualizo código aplicando buenas practicas.
